<?php
/**
 * @file
 * Drupal needs this blank file.
 */
 /**
 * Implements hook_form_alter().
 */
 function zurb_pantheon_form_alter(&$form, &$form_state, $form_id) {
   switch($form_id) {
   case 'user_register_form': // the value we stole from the rendered form
     $form['account']['mail']['#title'] = t('Work email');
     $form['account']['mail']['#description'] = FALSE;

     $form['field_first_name']['#prefix'] = '<div class="first_fname">';
     $form['field_first_name']['#suffix'] = '</div>';
     $form['field_last_name']['#prefix'] = '<div class="last_lname">';
     $form['field_last_name']['#suffix'] = '</div><div class="clearfix"></div>';
  //  $form['password'] = array(
  //   '#type' => 'password',
  //   '#title' => t('Password'),
  //  //  '#description' => t('Please enter your password'),
  //   '#size' => 32,
  //   '#maxlength' => 32,
  //   '#placeholder' => 'password',
  //   '#required' => TRUE,
  //   '#weight' => 9,
  //
  // );
  // Disable password
    $form['account']['pass']['#type'] = 'password';
    $form['account']['pass']['#title'] = 'Password';
    $form['account']['pass']['#description'] = FALSE;

    $form['checkbox'] = array(
      '#type' => 'checkbox',
      '#title' => '<span class="checkboxclass">Are you an agency?</span>(additional DevOps tools for agency developers)
      By creating an account, you agree to our <a href="#">Terms of service</a>',
      '#weight' => 10, // Adjust so that you can place it whereever
    );

    $form['mail'] = array(
      '#description' => FALSE,
      );
        break;
      }
    }
